### ISSUE TITLE
[mysql-explain] visit method error: javassist.CannotCompileException: cannot find com.mysql.cj.protocol.Message

### ISSUE THREAD

**Issue by dymice** [newhoo/mysql-explain#5]
这个版本会报错：
idea：2023.3
jdk：1.8
mysql-connector：8.0.29

![image](https://github.com/newhoo/mysql-explain/assets/26642453/cc5e9f9b-d31a-4cff-b977-afd09c397bc0)

```
[mysql-explain] visit method error: javassist.CannotCompileException: cannot find com.mysql.cj.protocol.Message
javassist.CannotCompileException: cannot find com.mysql.cj.protocol.Message
	at javassist.CtBehavior.insertBefore(CtBehavior.java:803)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:766)
	at io.github.newhoo.mysql.transformer.MySQLExplainTransformer.assistVisit(MySQLExplainTransformer.java:50)
	at io.github.newhoo.mysql.transformer.MySQLExplainTransformer.transform(MySQLExplainTransformer.java:34)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.mysql.cj.jdbc.ConnectionImpl.clientPrepareStatement(ConnectionImpl.java:670)
	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1643)
	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1658)
```

**Comment by newhoo** [comment]
同样的环境，我本地正常。试试clean，再重新编译。也可以单独启动jar，附上生成的jvm参数启动看看

**Comment by newhoo** [comment]
> 这个版本会报错： idea：2023.3 jdk：1.8 mysql-connector：8.0.29
> 
> ![image](https://private-user-images.githubusercontent.com/26642453/289428460-cc5e9f9b-d31a-4cff-b977-afd09c397bc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MjUyMjgsIm5iZiI6MTcwNDUyNDkyOCwicGF0aCI6Ii8yNjY0MjQ1My8yODk0Mjg0NjAtY2M1ZTlmOWItZDMxYS00Y2ZmLWI5NzctYWZkMDljMzk3YmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA3MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiN2U0NzJjZjBkNjgyMzA5MzMyNzlhZWE0N2JiY2I0Y2MyYWQxZTJkYmY3ZmJkMTBjZTc3MzAzOGM1ZWNmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qpvx7whd3qm2JPKgvTionHBwPaQGLFFTUCXMexYt6DY)
> 
> ```
> [mysql-explain] visit method error: javassist.CannotCompileException: cannot find com.mysql.cj.protocol.Message
> javassist.CannotCompileException: cannot find com.mysql.cj.protocol.Message
> 	at javassist.CtBehavior.insertBefore(CtBehavior.java:803)
> 	at javassist.CtBehavior.insertBefore(CtBehavior.java:766)
> 	at io.github.newhoo.mysql.transformer.MySQLExplainTransformer.assistVisit(MySQLExplainTransformer.java:50)
> 	at io.github.newhoo.mysql.transformer.MySQLExplainTransformer.transform(MySQLExplainTransformer.java:34)
> 	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
> 	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	at com.mysql.cj.jdbc.ConnectionImpl.clientPrepareStatement(ConnectionImpl.java:670)
> 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1643)
> 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1658)
> ```

部分项目环境会出现，和加载mysql的classloader有关。1.1.1做了兼容，升级试试。有问题再反馈
